name: .NET Core

on:
  push:
    branches: 
    - main
    - dev
  pull_request:
    branches: 
    - main
    - dev

env:
  AZURE_WEBAPP_NAME: contososaas
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: '5.0.*'             

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout submodules
      run: git submodule update --init       

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
     
    - name: Install dependencies
      run: dotnet restore 
      working-directory: ./src

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src

    - name: Publish
      run: dotnet publish CommandCenter.csproj -c Release --self-contained true -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
      working-directory: ./src

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'

