name: .NET Core

on:
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: 
      - dev
      - main

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        dotnet: ['3.1.*', '5.0' ]    

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}      

    - name: Build
      run: dotnet build --configuration Debug
      working-directory: ./src

    - name: test
      run: dotnet test
      env:
        TenantId: ${{secrets.TENANTID}}
        ClientId: ${{secrets.CLIENTID}}
        clientSecret: ${{secrets.CLIENTSECRET}}
      working-directory: .      
